FROM redis:8.6.0

RUN apt update -y && apt install -y iproute2 curl net-tools whois traceroute 

COPY redis.conf /usr/local/etc/redis/redis.conf
RUN chown -R redis.redis /usr/local/etc/redis

CMD  ["redis-server", "/usr/local/etc/redis/redis.conf"]
